<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sushi_factory"
 *
 * Auto generated by Extension Builder 2019-12-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sushi Factory',
    'description' => 'Template Extension für die Sushi Factory.',
    'category' => 'plugin',
    'author' => 'Oliver Schmidt',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
