base: /
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: 'Sushi Factory'
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: ab
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
    languageId: '0'
rootPageId: 7
routes: {  }
